from music import Chord, Quality, Note

class Standard:
    def __init__(self, name, *chords):
        self.__name   = name
        self.__chords = chords

    def __iter__(self):
        for chord in self.__chords:
            yield chord

standards = [
    Standard("Oleo",
        Chord(Quality.M, Note.I), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.III), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.V), Chord(Quality.dom, Note.I),
        Chord(Quality.dom, Note.IV), Chord(Quality.dom, Note.bVII),
        Chord(Quality.m, Note.III), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.M, Note.I), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.III), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.V), Chord(Quality.dom, Note.I),
        Chord(Quality.dom, Note.IV), Chord(Quality.dom, Note.bVII),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.M, Note.I), Chord(Quality.M, Note.I),
        Chord(Quality.dom, Note.III), Chord(Quality.dom, Note.III),
        Chord(Quality.m, Note.VII), Chord(Quality.dom, Note.III),
        Chord(Quality.dom, Note.VI), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.III), Chord(Quality.dom, Note.VI),
        Chord(Quality.dom, Note.II), Chord(Quality.dom, Note.II),
        Chord(Quality.m, Note.VI), Chord(Quality.dom, Note.II),
        Chord(Quality.dom, Note.V), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.M, Note.I), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.III), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.m, Note.V), Chord(Quality.dom, Note.I),
        Chord(Quality.dom, Note.IV), Chord(Quality.dom, Note.bVII),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.M, Note.I), Chord(Quality.M, Note.I)),
    Standard("Giant Steps",
        Chord(Quality.M, Note.I), Chord(Quality.dom, Note.bIII),
        Chord(Quality.M, Note.bVI), Chord(Quality.dom, Note.VII),
        Chord(Quality.M, Note.III), Chord(Quality.M, Note.III),
        Chord(Quality.m, Note.bVII), Chord(Quality.dom, Note.bIII),
        Chord(Quality.M, Note.bVI), Chord(Quality.dom, Note.VII),
        Chord(Quality.M, Note.III), Chord(Quality.dom, Note.V),
        Chord(Quality.M, Note.I), Chord(Quality.M, Note.I),
        Chord(Quality.m, Note.bV), Chord(Quality.dom, Note.VII),
        Chord(Quality.M, Note.III), Chord(Quality.M, Note.III),
        Chord(Quality.m, Note.bVII), Chord(Quality.dom, Note.bIII),
        Chord(Quality.M, Note.bVI), Chord(Quality.M, Note.bVI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V),
        Chord(Quality.M, Note.I), Chord(Quality.M, Note.I),
        Chord(Quality.m, Note.bV), Chord(Quality.dom, Note.VII),
        Chord(Quality.M, Note.III), Chord(Quality.M, Note.III),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V)),
    Standard("Blues for Alice",
        Chord(Quality.M, Note.I), Chord(Quality.M, Note.I),
        Chord(Quality.m, Note.VII), Chord(Quality.dom, Note.III),
        Chord(Quality.m, Note.VI), Chord(Quality.dom, Note.II),
        Chord(Quality.m, Note.V), Chord(Quality.dom, Note.I),
        Chord(Quality.M, Note.IV), Chord(Quality.M, Note.IV),
        Chord(Quality.m, Note.IV), Chord(Quality.dom, Note.bVII),
        Chord(Quality.m, Note.III), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.bIII), Chord(Quality.dom, Note.bVI),
        Chord(Quality.m, Note.II), Chord(Quality.m, Note.II),
        Chord(Quality.dom, Note.V), Chord(Quality.dom, Note.V),
        Chord(Quality.dom, Note.I), Chord(Quality.dom, Note.VI),
        Chord(Quality.m, Note.II), Chord(Quality.dom, Note.V)),
]